### ISSUE TITLE
Python 3.10 Support - `asyncio.sleep` dropped the `loop` keyword argument

### ISSUE THREAD

**Issue by zacharyrs** [Cinntax/pyenvisalink#27]
I'm running HomeAssistant with Python 3.10, which seems to have dropped the `loop` keyword argument to `asyncio.sleep`.

```
2022-05-16 23:49:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/var/lib/hass/venv/lib/python3.10/site-packages/pyenvisalink/dsc_client.py", line 50, in keep_alive
    await asyncio.sleep(self._alarmPanel.keepalive_interval, loop=self._eventLoop)
TypeError: sleep() got an unexpected keyword argument 'loop'
2022-05-16 23:49:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/var/lib/hass/venv/lib/python3.10/site-packages/pyenvisalink/dsc_client.py", line 57, in periodic_zone_timer_dump
    await asyncio.sleep(self._alarmPanel.zone_timer_interval, loop=self._eventLoop)
TypeError: sleep() got an unexpected keyword argument 'loop'
```

**Comment by autumnwalker** [comment]
Seeing this too in my HA 2022.07 install which moved to Python 3.10 by default.
